[package]
name = "kbd"
version = "0.1.0"

[dependencies]
wiring = { path = "../wiring" }
bit_field = "*"
byteorder = { version = "*", default-features = false }

[features]
#default = ["std"]
std = ["wiring/std"]
