[package]
name = "kbd_right_half"
version = "0.1.0"

[lib]
crate-type = ["staticlib"]

[dependencies]
wiring = { path = "../../wiring" }
kbd = { path = "../../kbd" }
framed = { path = "../../framed" }
futures = {version="*", default-features=false, features = []}
